# Generated by Django 6.0.3 on 2026-03-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('cellphone', models.CharField(max_length=15)),
                ('category', models.CharField(choices=[('ELEC', '⚡ Electricity'), ('WLEAK', '💧 Water Leak'), ('BPIPE', '🌊 Burst Pipe'), ('MHOLE', '🕳️ Missing Manhole'), ('RUBBL', '🏗️ Rubble'), ('STORM', '⛈️ Storm Water'), ('SANI', '🚽 Sanitation'), ('POTH', '🚧 Pothole'), ('OTHER', '🌳 Other')], max_length=10)),
                ('location_address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fault_images/')),
                ('audio_report', models.FileField(blank=True, null=True, upload_to='fault_audio/')),
                ('status', models.CharField(choices=[('LOG', 'Logged'), ('DIS', 'Dispatched'), ('PROG', 'In Progress'), ('RES', 'Resolved')], default='LOG', max_length=10)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_reported'],
            },
        ),
    ]
