# Generated by Django 6.0.3 on 2026-03-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('water', 'Water/Sanitation'), ('elec', 'Electricity'), ('road', 'Roads/Potholes')], max_length=20)),
                ('description', models.TextField()),
                ('location_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('logged', 'Logged'), ('dispatched', 'Dispatched'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='logged', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fault_pics/')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
