# Generated by Django 6.0.3 on 2026-03-30 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='ref_number',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AffectedResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('cellphone', models.CharField(max_length=15)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_residents', to='map.fault')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
