# Generated by Django 6.0.3 on 2026-03-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fault',
            options={'ordering': ['-date_reported']},
        ),
        migrations.RenameField(
            model_name='fault',
            old_name='date_submitted',
            new_name='date_reported',
        ),
        migrations.AlterField(
            model_name='fault',
            name='category',
            field=models.CharField(choices=[('ELEC', '⚡ Electricity Problems'), ('WLEAK', '💧 Water Leaks'), ('BPIPE', '🌊 Burst Pipes'), ('MHOLE', '🕳️ Missing Manhole Covers'), ('RUBBL', '🏗️ Rubble'), ('STORM', '⛈️ Storm Water System Problems'), ('SANI', '🚽 Sanitation System Problems'), ('POTH', '🚧 Potholes & Road Problems'), ('OTHER', '🌳 Parks, Open Areas & Other')], help_text='Select the type of infrastructure issue', max_length=5),
        ),
        migrations.AlterField(
            model_name='fault',
            name='description',
            field=models.TextField(help_text='Provide more details about the problem'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fault_images/'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='location_address',
            field=models.CharField(help_text='e.g., 10 Market Square, Kimberley', max_length=255),
        ),
        migrations.AlterField(
            model_name='fault',
            name='status',
            field=models.CharField(choices=[('LOG', 'Logged'), ('DIS', 'Dispatched'), ('PROG', 'In Progress'), ('RES', 'Resolved')], default='LOG', max_length=4),
        ),
    ]
