# Generated by Django 6.0.3 on 2026-03-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_fault_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='audio_report',
            field=models.FileField(blank=True, null=True, upload_to='fault_audio/'),
        ),
        migrations.AddField(
            model_name='fault',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='fault',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='fault',
            name='category',
            field=models.CharField(choices=[('ELEC', '⚡ Electricity Problems'), ('WLEAK', '💧 Water Leaks'), ('BPIPE', '🌊 Burst Pipes'), ('MHOLE', '🕳️ Missing Manhole Covers'), ('RUBBL', '🏗️ Rubble'), ('STORM', '⛈️ Storm Water System Problems'), ('SANI', '🚽 Sanitation System Problems'), ('POTH', '🚧 Potholes & Road Problems'), ('OTHER', '🌳 Parks, Open Areas & Other')], max_length=5),
        ),
        migrations.AlterField(
            model_name='fault',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fault',
            name='location_address',
            field=models.CharField(help_text='Street name or landmark', max_length=255),
        ),
    ]
