# Generated by Django 6.0.3 on 2026-03-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_fault_audio_report_fault_latitude_fault_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='cellphone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fault',
            name='full_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fault',
            name='category',
            field=models.CharField(choices=[('ELEC', '⚡ Electricity Problems'), ('WLEAK', '💧 Water Leaks'), ('BPIPE', '🌊 Burst Pipes'), ('MHOLE', '🕳️ Missing Manhole Covers'), ('RUBBL', '🏗️ Rubble'), ('STORM', '⛈️ Storm Water System'), ('SANI', '🚽 Sanitation System'), ('POTH', '🚧 Potholes & Road Problems'), ('OTHER', '🌳 Parks & Open Areas')], max_length=5),
        ),
        migrations.AlterField(
            model_name='fault',
            name='location_address',
            field=models.CharField(max_length=255),
        ),
    ]
