# Generated by Django 6.0.3 on 2026-03-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_fault_cellphone_fault_full_name_alter_fault_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='category',
            field=models.CharField(choices=[('ELEC', '⚡ Electricity'), ('WLEAK', '💧 Water Leak'), ('BPIPE', '🌊 Burst Pipe'), ('MHOLE', '🕳️ Missing Manhole'), ('RUBBL', '🏗️ Rubble'), ('STORM', '⛈️ Storm Water'), ('SANI', '🚽 Sanitation'), ('POTH', '🚧 Pothole'), ('OTHER', '🌳 Other')], max_length=5),
        ),
        migrations.AlterField(
            model_name='fault',
            name='description',
            field=models.TextField(blank=True, help_text='Manual report details', null=True),
        ),
        migrations.AlterField(
            model_name='fault',
            name='location_address',
            field=models.CharField(help_text='Can be auto-filled or manual', max_length=255),
        ),
    ]
