# Generated by Django 6.0.3 on 2026-03-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_fault_category_alter_fault_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fault',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fault',
            name='location_address',
            field=models.CharField(max_length=255),
        ),
    ]
