# Generated by Django 6.0.3 on 2026-03-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_fault_description_alter_fault_location_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fault',
            name='audio_report',
        ),
        migrations.AlterField(
            model_name='fault',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fault',
            name='location_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fault',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
